apiVersion: v1
kind: ServiceAccount
metadata:
  name: login-app-sa
  namespace: login-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: login-app
  name: login-app-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: login-app-rolebinding
  namespace: login-app
subjects:
- kind: ServiceAccount
  name: login-app-sa
  namespace: login-app
roleRef:
  kind: Role
  name: login-app-role
  apiGroup: rbac.authorization.k8s.io