apiVersion: v1
kind: Service
metadata:
  name: login-app-service
  namespace: login-app
spec:
  selector:
    app: login-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30341
  type: NodePort